# Uncomment the next line to define a global platform for your project
platform :ios, '14.7'

target 'ModelVale' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  use_modular_headers!

  # Pods for ModelVale
  pod 'QBImagePickerController'
  pod 'iOSDropDown'
  pod 'FirebaseAuth'
  pod 'FirebaseFirestore'
  pod 'FirebaseStorage'
  pod 'GTMAppAuth'
  pod 'AppAuth'
  pod 'GoogleAPIClientForREST/Drive'
  #pod 'GoogleSignIn'
  #pod 'GTMSessionFetcher/Core', '>= 1.0', '< 3.0'
  

  target 'ModelValeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ModelValeUITests' do
    # Pods for testing
  end

end
